PBYD - PlayBeforeYouDie/Controllers/GameOfTheYearController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayBeforeYouDie.Core.Contracts;

namespace PBYD___PlayBeforeYouDie.Controllers
{
    [Authorize]
    public class GameOfTheYearController : Controller
    {
        private readonly IGameOfTheYearService gameOfTheYearService;

        public GameOfTheYearController(IGameOfTheYearService _gameOfTheYearService)
        {
            gameOfTheYearService = _gameOfTheYearService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GotyAllView()
        {
            try
            {
                var model = await gameOfTheYearService.GetAllGotyAsync();

                return View(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Database is down or game of the year does not exists");
                
                return View("_Layout", "Index");
            }
            
        }
    }
}

PBYD - PlayBeforeYouDie/Controllers/HowLongToBeatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PBYD___PlayBeforeYouDie.Extensions;
using PlayBeforeYouDie.Core.Contracts;
using PlayBeforeYouDie.Core.Models.Game;
using PlayBeforeYouDie.Core.Models.HowLongToBeat;
using PlayBeforeYouDie.Infrastructure.Data.Models;

namespace PBYD___PlayBeforeYouDie.Controllers
{
    [Authorize]
    public class HowLongToBeatController : Controller
    {

        private readonly ILogger logger;
        private readonly IHowLongToBeatService howLongToBeat;
        private readonly IGameService gameService;

        public HowLongToBeatController(
            ILogger<HowLongToBeatController> _logger, IHowLongToBeatService _howLongToBeat, IGameService _gameService)
        {
            logger = _logger;
            howLongToBeat = _howLongToBeat;
            gameService = _gameService;
        }

        [AllowAnonymous]
        public async  Task<IActionResult> HowLongToBeatView()
        {

            var model = await gameService.GetInitialGames();

            return View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> HowLongGame(int id)
        {
            if (await gameService.Exists(id) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";
                return RedirectToAction("AllGames", "Game");
            }

            try
            {
                var model = await howLongToBeat.GameHowLongToBeatById(id);

                return View(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError(nameof(id), "Game id does not exists");

                return View(nameof(HowLongToBeatView));
            }

            
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Submit(int gameId)
        {
            if (await gameService.Exists(gameId) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";

                return RedirectToAction("AllGames", "Game");
            }

            try
            {
                var model = new HowLongToBeatModel();

                model.GameId = gameId;

                return View(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError(nameof(gameId), "Game id does not exists");

                return View(nameof(HowLongGame));
            }

            
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Submit(HowLongToBeatModel model)
        {
            
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Wrong model";
                return View(model);
            }

            try
            {
                await howLongToBeat.SubmitPlayTime(model);

                return RedirectToAction(nameof(HowLongGame), new { id = model.GameId });
            }

            catch (Exception)
            {
                ModelState.AddModelError("", "Game model does not exists");

                return View(nameof(HowLongGame));
            }

            

        }
    }
}

PBYD - PlayBeforeYouDie/Controllers/ModController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayBeforeYouDie.Core.Contracts;
using PlayBeforeYouDie.Core.Models.Mod;
using PlayBeforeYouDie.Infrastructure.Data.Models;


namespace PBYD___PlayBeforeYouDie.Controllers
{
    [Authorize]
    public class ModController : Controller
    {
        private readonly ILogger logger;
        private readonly IModService modService;
        private readonly IGameService gameService;

        public ModController(ILogger<ModController> _logger, IModService _modService, IGameService _gameService)
        {
            logger = _logger;
            modService = _modService;
            gameService = _gameService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> ModsView()
        {
            var model = await gameService.GetInitialGames();

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ModsGame(int id)
        {
            if (await gameService.Exists(id) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";
                
                return RedirectToAction("AllGames", "Game");
            }

            try
            {
                var model = await modService.ModsByGameById(id);

                return View(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError(nameof(id), "Game id does not exists");

                return View(nameof(ModsView));
            }

            
        }


        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Create(int gameId)
        {
            if (await gameService.Exists(gameId) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";
                return RedirectToAction("AllGames", "Game");
            }

            try
            {
                var model = new ModModel();

                model.GameId = gameId;

                return View(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError(nameof(gameId), "Game id does not exists");

                return View(nameof(ModsView));
            }

            
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Create(ModModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Wrong model!";
                return View(model);
            }

            try
            {
                await modService.SubmitMod(model);

                return RedirectToAction(nameof(ModsGame), new { id = model.GameId });
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Mod model does not exists");

                return View(nameof(ModsView));
            }
            
        }
    }
}

PBYD - PlayBeforeYouDie/Controllers/SystemRequirementsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayBeforeYouDie.Core.Contracts;
using PlayBeforeYouDie.Core.Models.SystemRequirement;
using PlayBeforeYouDie.Core.Service;
using PlayBeforeYouDie.Infrastructure.Data.Models;

namespace PBYD___PlayBeforeYouDie.Controllers
{
    [Authorize]
    public class SystemRequirementsController : Controller
    {
        private readonly ILogger logger;
        private readonly ISystemRequirementsService systemRequirementsService;
        private readonly IGameService gameService;

        public SystemRequirementsController(ILogger<SystemRequirementsController> _logger,
            ISystemRequirementsService _systemRequirementsService,
            IGameService _gameService)
        {
            logger = _logger;
            systemRequirementsService = _systemRequirementsService;
            gameService = _gameService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> SystemRequirementsGame(int id)
        {
            if (await gameService.Exists(id) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";
                
                return RedirectToAction("AllGames", "Game");
            }

            try
            {
                var model = await systemRequirementsService.SystemRequirementsGameById(id);

                return View(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError(nameof(id), "game id does not exists");

                return View("_Layout");
            }

            
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Edit(int systemRequirementsId)
        {
            if (await systemRequirementsService.SystemRequirementsExists(systemRequirementsId) == false)
            {
                TempData["ErrorMessage"] = "Wrong systemRequirements id!";

                return RedirectToAction(nameof(SystemRequirementsGame));
            }

            try
            {
                var game = await systemRequirementsService.SystemRequirementsDetailsById(systemRequirementsId);

                var model = new SystemRequirementsModel()
                {
                    Os = game.Os,
                    Graphics = game.Os,
                    Memory = game.Memory,
                    Processor = game.Processor,
                    Network = game.Network,
                    Storage = game.Storage,
                    AdditionalNotes = game.AdditionalNotes
                };

                return View(model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError(nameof(systemRequirementsId), "System Requirements id does not exists or game is empty");

                return View(nameof(SystemRequirementsGame));
            }
            
            
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Edit(SystemRequirementsModel model, int systemRequirementsId)
        {
            if (systemRequirementsId != model.systemRequirementsId)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            if (await systemRequirementsService.SystemRequirementsExists(systemRequirementsId) == false)
            {
                TempData["ErrorMessage"] = "Wrong systemRequirements id!";
                
                return RedirectToAction(nameof(SystemRequirementsGame));
            }

            if (ModelState.IsValid == false)
            {
                TempData["ErrorMessage"] = "Wrong model!";
                
                return View(model);
            }

            try
            {
                await systemRequirementsService.Edit(model.Id = systemRequirementsId, model);

                return RedirectToAction(nameof(SystemRequirementsGame));
            }
            catch (Exception)
            {
                ModelState.AddModelError(nameof(systemRequirementsId), "System Requirements id does not exists");

                return View(nameof(SystemRequirementsGame));
            }

        }
    }
}

PBYD - PlayBeforeYouDie/Views/Shared/_GameFormPartial.cshtml
@model AddGameModel

<div class="col-md-4" style="width:550px; margin:0 auto;">
    <div class="card mb-3">
        <div class="card-body text-center" style="color:aqua">
            <p>
                Make sure you've researched the game before adding it the game-list, PBYD tries to make the selected game as informative as possible, 
                few websites that might help you find what you need:
                
              
            </p>
        </div>
        <ul>
            <li><a href="https://www.nexusmods.com/" target="_blank">Nexus Mods</a></li>
            <li><a href="https://howlongtobeat.com/" target="_blank">How Long To Beat</a></li>
            <li><a href="https://www.pcgamebenchmark.com/" target="_blank">PC Requirements</a></li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-group">
                <label asp-for="GameTitle"></label>
                <input asp-for="GameTitle" class="form-control" placeholder="Title...">
                <span asp-validation-for="GameTitle" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary"></label>
                <input asp-for="Summary" class="form-control" placeholder="Game Summary...">
                <span asp-validation-for="Summary" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Game Image URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating"></label>
                <input asp-for="Rating" class="form-control">
                <span asp-validation-for="Rating" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="GenreId"></label>
                <select asp-for="GenreId" class="form-control">
                    @foreach (var genre in Model.Genres)
                    {
                        <option value="@genre.Id">@genre.Category</option>
                    }
                </select>
                <span asp-validation-for="GenreId" class="small text-danger"></span>
            </div>
            
            <p>
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExampleOne" aria-expanded="false" aria-controls="collapseExample">
                    Click to Add System Requirements for the game!
                </button>
            </p>

            <div class="collapse" id="collapseExampleOne">
                <div class="form-group">
                    <label asp-for="@Model.Os"></label>
                    <input asp-for="@Model.Os" class="form-control" placeholder="Platform...">
                    <span asp-validation-for="@Model.Os" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Processor"></label>
                    <input asp-for="@Model.Processor" class="form-control" placeholder="Processor...">
                    <span asp-validation-for="@Model.Processor" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Memory"></label>
                    <input asp-for="@Model.Memory" class="form-control" placeholder="Memory...">
                    <span asp-validation-for="@Model.Memory" class="small text-danger"></span>
                </div>
                <div class="form-group"><label asp-for="@Model.Graphics"></label>
                    <input asp-for="@Model.Graphics" class="form-control" placeholder="Graphics...">
                    <span asp-validation-for="@Model.Graphics" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Network"></label>
                    <input asp-for="@Model.Network" class="form-control" placeholder="Network...">
                    <span asp-validation-for="@Model.Network" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Storage"></label>
                    <input asp-for="@Model.Storage" class="form-control" placeholder="Storage...">
                    <span asp-validation-for="@Model.Storage" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.AdditionalNotes"></label>
                    <input asp-for="@Model.AdditionalNotes" class="form-control" placeholder="Optional AdditionalNotes...">
                    <span asp-validation-for="@Model.AdditionalNotes" class="small text-danger"></span>
                </div>
            </div>
            
            <p>
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExampleTwo" aria-expanded="false" aria-controls="collapseExample">
                    Click to Add Mods for the Game!
                </button>
            </p>

            <div class="collapse" id="collapseExampleTwo">
                <div class="form-group">
                    <label asp-for="ModName"></label>
                    <input asp-for="ModName" class="form-control" placeholder="Mod Name...">
                    <span asp-validation-for="ModName" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" placeholder="Mod Description...">
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DownloadModLink"></label>
                    <input asp-for="DownloadModLink" class="form-control" placeholder="Download Mod Link...">
                    <span asp-validation-for="DownloadModLink" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="YoutubeVideoModComparison"></label>
                    <input asp-for="YoutubeVideoModComparison" class="form-control" style="color: red" placeholder="Optional Youtube Vid for Mod, Format Example: https://youtube/embed/urlcode..">
                    <span asp-validation-for="YoutubeVideoModComparison" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ModImageOne"></label>
                    <input asp-for="ModImageOne" class="form-control" placeholder="Mod Image One Link...">
                    <span asp-validation-for="ModImageOne" class="small text-danger"></span>
                </div>
            </div>
            
            <p>
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExampleThree" aria-expanded="false" aria-controls="collapseExample">
                    Click to Add Playtime for the Game!
                </button>
            </p>
            
            <div class="collapse" id="collapseExampleThree">
                <div class="form-group">
                    <label asp-for="MainStory"></label>
                    <input asp-for="MainStory" class="form-control" placeholder="00h 00m 00s...">
                    <span asp-validation-for="MainStory" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MainPlusSides"></label>
                    <input asp-for="MainPlusSides" class="form-control" placeholder="00h 00m 00s...">
                    <span asp-validation-for="MainPlusSides" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="HundredPercentComplete"></label>
                    <input asp-for="HundredPercentComplete" class="form-control" placeholder="00h 00m 00s...">
                    <span asp-validation-for="HundredPercentComplete" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SpeedRunAny"></label>
                    <input asp-for="SpeedRunAny" class="form-control" placeholder="Optional Speed Run Times! 00h 00m 00s...">
                    <span asp-validation-for="SpeedRunAny" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SpeedRunOneHundredPercent"></label>
                    <input asp-for="SpeedRunOneHundredPercent" class="form-control" placeholder="Optional Speed Run Times! 00h 00m 00s...">
                    <span asp-validation-for="SpeedRunOneHundredPercent" class="small text-danger"></span>
                </div>
            </div>
            
             
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Add"/>
            </div>          
              

        </form>
        
        
    </div>
</div>

PBYD - PlayBeforeYouDie/Views/Shared/_GamePartial.cshtml
@model GameServiceModel

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <img class="card-img-top "
                 src="@Model.ImageUrl" alt="Game Image">
            <div class="card-body">

                <h5 class="card-title mt-1">@Model.GameTitle</h5>
                <p class="m-1" style="color:red;">Metacritic Rating: @Model.Rating</p>
                
                <div style="min-height: 15px;">
                    <div class="collapse collapse-horizontal" id="collapseWidthExample">
                        <div class="card card-body" style="width: 350px;">
                            @Model.Summary
                        </div>
                    </div>
                </div>

            </div>
            
            <a asp-area="" asp-controller="Mod" asp-action="ModsGame" asp-route-id="@Model.Id"
               class="fs-6 btn btn-success mb-3 p-2">Mods</a>

            <a asp-area="" asp-controller="HowLongToBeat" asp-action="HowLongGame" asp-route-id="@Model.Id"
               class="fs-6 btn btn-success mb-3 p-2">HowLongToBeat</a>

            <a asp-area="" asp-controller="SystemRequirements" asp-action="SystemRequirementsGame" asp-route-id="@Model.Id"
               class="fs-6 btn btn-success mb-3 p-2" style="background-color: #b58900">System Requirements</a>
            
            @if (User?.Identity?.IsAuthenticated ?? false)
            {
                <form class="input-group-sm" asp-area="" asp-controller="Game"
                      asp-action="AddToCollection" asp-route-id="@Model.Id" method="post">
                    <input class="btn btn-primary" type="submit" value="AddToCollection" />
                </form>

                
            }
            @if (User!.IsInRole("Administrator"))
            {

                <a style="margin: 40px" asp-area="Admin" asp-controller="Game" asp-action="Delete" asp-route-id="@Model.Id"
                   class="btn btn-primary btn-sm">Delete</a>

                <a style="margin: 40px" asp-area="Admin" asp-controller="Game" asp-action="Edit" asp-route-id="@Model.Id"
                   class="btn btn-primary btn-sm">Edit</a>
            }
            
        </div>
    </div>
    
</div>

PBYD - PlayBeforeYouDie/Views/Shared/_HowLongToBeatPartial.cshtml
@model HowLongToBeatModel


<div class="col-md-4" style="width:550px; margin:0 auto;">
    <div class="card mb-3">
        <div class="card-body text-center">
            <p>
                Submit your playtime for the game! Speed runs are optional
            </p>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="@Model.Id" />
            
            <div class="form-group">
                <label asp-for="MainStory"></label>
                <input asp-for="MainStory" class="form-control" placeholder="00h 00m 00s...">
                <span asp-validation-for="MainStory" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainPlusSides"></label>
                <input asp-for="MainPlusSides" class="form-control" placeholder="00h 00m 00s...">
                <span asp-validation-for="MainPlusSides" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HundredPercentComplete"></label>
                <input asp-for="HundredPercentComplete" class="form-control" placeholder="00h 00m 00s...">
                <span asp-validation-for="HundredPercentComplete" class="small text-danger"></span>
            </div>
            <p>
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExampleOne" aria-expanded="false" aria-controls="collapseExample">
                    Optional Speed Run Times!
                </button>
            </p>
            
            <div class="collapse" id="collapseExampleOne">
                <div class="form-group">
                    <label asp-for="SpeedRunAny"></label>
                    <input asp-for="SpeedRunAny" class="form-control" placeholder="00h 00m 00s...">
                    <span asp-validation-for="SpeedRunAny" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SpeedRunOneHundredPercent"></label>
                    <input asp-for="SpeedRunOneHundredPercent" class="form-control" placeholder="00h 00m 00s...">
                    <span asp-validation-for="SpeedRunOneHundredPercent" class="small text-danger"></span>
                </div>
            </div>
            
            
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save"/>
            </div>
        </form>
    </div>
</div>

PBYD - PlayBeforeYouDie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PBYD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="lib/toastr/toastr.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PBYD___PlayBeforeYouDie.styles.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="~/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PlayBeforeYouDie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <div class="dropdown">
                            <button style="margin:5px" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                                Game Library
                            </button>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">

                                @if (User?.Identity?.IsAuthenticated ?? false)
                                {
                                    <a class="nav-link text-light" asp-area="" asp-controller="Game" asp-action="MyGamesLibrary">My Games</a>
                                    <li><hr class="dropdown-divider"></li>
                                    <a class="nav-link text-light" asp-area="" asp-controller="Mod" asp-action="ModsView">Mods</a>
                                    <li><hr class="dropdown-divider"></li>
                                    <a class="nav-link text-light" asp-area="" asp-controller="HowLongToBeat" asp-action="HowLongToBeatView">How Long To Beat</a>
                                   
                                }
                                else
                                {
                                    <li>
                                        <a class="dropdown-item active" asp-controller="User" asp-action="Login">Please login to view your games and mods!</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <a class="nav-link text-light" asp-area="" asp-controller="HowLongToBeat" asp-action="HowLongToBeatView">How Long To Beat</a>
                                    <li><hr class="dropdown-divider"></li>
                                    <a class="nav-link text-light" asp-area="" asp-controller="Mod" asp-action="ModsView">Mods</a>
                                }

                            </ul>
                        </div>
                        <div class="dropdown">
                            <button style="margin:5px" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton3" data-bs-toggle="dropdown" aria-expanded="false">
                                Top Games Overall
                            </button>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                                <a class="nav-link text-light" asp-area="" asp-controller="GameOfTheYear" asp-action="GotyAllView">Game of the Year Collection</a>
                                <li><hr class="dropdown-divider"></li>
                                <a class="nav-link text-light" asp-area="" asp-controller="Game" asp-action="AllGames">Top Rated Games According to Metacritic</a>
                            </ul>
                        </div>
                    </ul>
                    

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <ul class="nav justify-content-center">
            <div class="text-center">
                &copy; @DateTime.UtcNow.Year - Play Before You Die
            </div>
        </ul>
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="lib/toastr/toastr.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PBYD - PlayBeforeYouDie/Views/Shared/_TestPartial.cshtml
@model AddGameModel