PBYD - PlayBeforeYouDie/Areas/Admin/Controllers/GameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PBYD___PlayBeforeYouDie.Areas.Admin.Models;
using PBYD___PlayBeforeYouDie.Areas.Admin.Models.Game;
using PBYD___PlayBeforeYouDie.Models;
using PlayBeforeYouDie.Core.Contracts;
using PlayBeforeYouDie.Core.Models.Game;

namespace PBYD___PlayBeforeYouDie.Areas.Admin.Controllers
{
    public class GameController : BaseController
    {
        private readonly IGameService gameService;

        public GameController(IGameService _gameService)
        {
            gameService = _gameService;
        }

        [HttpGet]
        public async Task<IActionResult> AllGames([FromQuery] AdminGamesViewModel query)
        {
            try
            {
                var result = await gameService.All(query.Genre,
                    query.SearchGame,
                    query.CurrentPage,
                    AdminGamesViewModel.HousesPerPage);

                query.TotalGamesCount = result.TotalGamesCount;
                query.Genres = await gameService.AllGenreNames();
                query.Games = result.Games;

                return View(query);
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Database is down or games does not exists");

                return View(nameof(AllGames));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await gameService.Exists(id) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";

                return RedirectToAction(nameof(AllGames));
            }

            var game = await gameService.GameEditModelById(id);
            var genreId = await gameService.GetGameGenreById(id);

            var model = new GameModel()
            {
                Id = game.Id,
                GameTitle = game.GameTitle,
                Rating = game.Rating,
                Summary = game.Summary,
                ImageUrl = game.ImageUrl,
                GenreId = genreId,
                Genres = await gameService.AllGenres()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, GameModel model)
        {
            if (id != model.Id)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            if (await gameService.Exists(model.Id) == false)
            {
                ModelState.AddModelError("", "Database is down or games does not exists");
                model.Genres = await gameService.AllGenres();

                return View(model);
            }

            if (await gameService.GenreExists(model.GenreId) == false)
            {
                ModelState.AddModelError("", "Database is down or genre does not exists");

                model.Genres = await gameService.AllGenres();

                return View(model);
            }

            if (ModelState.IsValid == false)
            {
                TempData["ErrorMessage"] = "Wrong model!";
                model.Genres = await gameService.AllGenres();

                return View(model);
            }

            await gameService.EditGame(model, model.Id);

            return RedirectToAction(nameof(AllGames), new { id = model.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await gameService.Exists(id) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";

                return RedirectToAction(nameof(AllGames));
            }

            try
            {
                var game = await gameService.DeleteGameById(id);
                var model = new GameDeleteViewModel()
                {
                    GameTitle = game.GameTitle,
                    ImageUrl = game.ImageUrl,
                    Description = game.Summary,
                    Rating = game.Rating
                };

                return View(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Database is down or games does not exists");

                return View(nameof(AllGames));
            }


        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, GameServiceModel model)
        {
            if (await gameService.Exists(id) == false)
            {
                TempData["ErrorMessage"] = "Wrong game id!";

                return RedirectToAction(nameof(AllGames));
            }

            try
            {
                await gameService.DeleteGame(id);

                return RedirectToAction(nameof(AllGames));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Database is down or games does not exists");

                return View(nameof(AllGames));
            }
        }
    }
}

PBYD - PlayBeforeYouDie/Areas/Admin/Views/Admin/Index.cshtml
@model IEnumerable<GameHomeModel>

@{
    ViewData["Title"] = "Home Page";

    bool first = true;
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/CSS/AdminImage.css" />
</head>

<div class="text-center" >
<h1 style="color: #b58900">Welcome to Play Before You Die Admin World ! <span class="badge bg-secondary">PBYD</span></h1>
<h4 style="color: aqua">This is the Admin View where you can delete/edit/change anything and improve the website for the best needs of the users
</h4>
</div>

<div class="text-center">
    <a class="btn btn-primary btn-lg" asp-area="" asp-controller="Game" asp-action="AllGames">View Game Collection</a>
</div>

<h4 style="color: #b58900">Games Summary:</h4>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        @foreach (var games in @Model)
        {
            <div class="carousel-item @(first ? "active" : string.Empty)">

                <img class="d-block w-100" style="width:100px; margin:0 auto;"
                     src="@games.ImageUrl" alt="@games.GameTitle">
                <div class="carousel-caption d-none d-md-block">
                    <h5>
                        <a class="btn btn-primary" asp-controller="Game" asp-action="Delete" asp-route-id="@games.Id"
                           asp-route-id="@games.Id">
                            Delete - @games.GameTitle</a>
                    </h5>
                    <h5>
                        <a class="fs-6 btn btn-success mb-3 p-2" asp-controller="Game" asp-action="Edit" asp-route-id="@games.Id"
                           asp-route-id="@games.Id">
                            Edit - @games.GameTitle</a>
                    </h5>
                </div>
            </div>

            @(first = false)
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>